### PR TITLE
Bump version requirement for json-schema

### LINKED ISSUE #439: __autoload() is deprecated, use spl_autoload_register() instead
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.8.0@e7d8df3 2019-06-08 14:25:00 UTC
| PHP version | PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1
| Platform with version | Ubuntu
| Github Repo | infection/infection

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "output": "build/infection.phar",

    "git-version": "package_version",

    "compression": "GZ",
    "compactors": [
        "KevinGH\\Box\\Compactor\\Json",
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\PhpScoper"
    ],
    "files": ["resources/schema.json"]
}
 ```
</details>

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
<?php

return [
    'whitelist' => [
        "Safe\\*"
    ],
];
 ```

</details>

When the phar is compiled and executed, the following deprecation warnings are displayed:

```bash
PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in phar:///infection/build/infection.phar/vendor/autoload.php on line 78

Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in phar:///infection/build/infection.phar/vendor/autoload.php on line 78
You are running Infection with PCOV enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...
```

This issue is not reproduced without `scoper.inc.php`

Related to https://github.com/infection/infection/issues/795

### PR DESCRIPTION
**Pull request by sanmai**
Fixes #439

(This is not yet a released version, so builds will naturally fail.)

### CODE REVIEW

**Comment by sanmai** [comment]
This bump might be unnecessary, but, as earlier versions are known to cause #439 in PHP 7.2 and later, this change makes sure that #439 goes away for good.

**Comment by theofidry** [comment]
I'm fine with the bump. I've restarted the build :)

**Comment by sanmai** [comment]
The package didn't [get to the Packagist](https://packagist.org/packages/justinrainbow/json-schema) for some reason.

**Comment by pxgamer** [comment]
Looks like it's on Packagist now, so in theory this should work if re-run. 🤔

**Comment by theofidry** [comment]
Will make it pass in #443

**Comment by theofidry** [comment]
release in 3.8.2

**Pull request merged**
