### PR TITLE
Fix usage of Box when installed globally

### LINKED ISSUE #84: Breaks entire composer installation due to bad autoload rules
Happening: since 3995ac0de95cc86c523571fb509e775625df112a

Steps to reproduce:
```
composer global require 'humbug/php-scoper:^1.0@dev'
composer global require humbug/box:dev-master
```
After this composer global commands (even unrelated, like `show -i`) will fail with `failed opening required(/home/weirdan/.composer/vendor/composer/../humbug/box/vendor/humbug/php-scoper/src/functions.php)`

When box is installed globally (or as a dependency of some other project) it doesn't have `vendor` subfolder. It's dependencies are in sibling folders instead.

Suggested fix: put that file in `autoload/files` section of php-scoper, remove here.

### PR DESCRIPTION
**Pull request by theofidry**
Closes #84

### CODE REVIEW

**Comment by theofidry** [comment]
@kelunik could you enlighten me on how the bootstrapping process occurs with the workers with amphp? I couldn't find anything on it

**Comment by kelunik** [comment]
What do you mean? When they start up?

**Comment by theofidry** [comment]
Yes. When Box starts (via `bin/box`), I load the Composer autoloader as well as PHPScoper `functions.php` file. That one is not registered _yet_ via Composer to be able to perform [some checks](https://github.com/humbug/php-scoper/blob/master/bin/php-scoper#L63) before `functions.php` is loaded.

I noticed that when the workers are running (see this [bit](https://github.com/humbug/box/blob/master/src/Box.php#L337-L338) executed with `parallelMap()`, 1. the working directory can be wrong and 2. the PHPScoper `functions.php` file is not loaded. However it's not as if _nothing_ is loaded either as the Composer autoloading seems to be working fine still

**Comment by kelunik** [comment]
It starts the workers as soon as they're needed. The Composer autoloader is automatically included, so those things just work. The solution is to do these additional checks in a file that's autoloaded by Composer. I guess the workers just take the working directory when they're started, they don't care to normalize it. Might be a good idea to do that.

The worker script is [here](https://github.com/amphp/parallel/blob/dbdc7895ac9d059e3560cae99703c85caffa811e/lib/Context/Internal/process-runner.php).

**Comment by theofidry** [comment]
Thanks! I see. Maybe it would be easier if there's an entry point to register a custom bootstrapper. However I plan to remove that weird piece of code from PHP-Scoper as well so it might not be worth it

**Comment by kelunik** [comment]
@theofidry The composer autoloader is already a single place where it can be done. If you only need to run something in the worker, you can check the `AMP_WORKER` constant. For a custom bootstrapper you'd need a separate pool, otherwise two libraries replacing the bootstrapper would conflict.

**Comment by theofidry** [comment]
Ok I'll look into the separate pool then! With PHP-Scoper the autoloading file is no longer `vendor/autoload.php` as well but `vendor/scoper-autoload.php` so I still may need that at some point

**Pull request merged**
